RWKV:
  layers: [0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30]
  grap_cp: 1

Llama:
  model_id: /data/rwkv/models/meta-llama/Meta-Llama-3.1-8B-Instruct/

kl_weight: 0.1
ce_weight: 1
model_file: Llama3.18BInstructRWKV8Layers